fix: remove use of format in favour of inline bash
action-stars/install-tool-from-github-release pull request #2
Opened 2023-11-06 14:52 UTC by quotidian-ennui

# Motivation

Resolves #1

## Changes

- Use inline bash to derive the supported platform_urls
- Add specific test to confirm fix
- Fixed a minor copy & paste error around platform descs

2023-11-24 10:39 UTC, quotidian-ennui commented
@stevehipwell  -> Steve, you might want to have a CODEOWNERS or similar to assign yourself to review this ;)

2023-11-29 13:42 UTC, stevehipwell requested changes
I've added a _nit_ comment for the bash script. Could you also split the PR in half so we can get the action changes merged ASAP.

RE the tests I think a matrix job driven from a YAML file processed in a pre-job would be the best way to make this extensible.

2023-11-29 13:42 UTC, stevehipwell commented on action.yml
> +        fi
```suggestion
        set -euo pipefail
        
        if [[ -n "${{ inputs.filename_format_linux }}" ]]
        then
          echo "linux_url=https://github.com/${{ inputs.owner }}/${{ inputs.repository }}/releases/download/${{ inputs.tag_prefix }}{version}/${{ inputs.filename_format_linux }}" >> "${GITHUB_OUTPUT}"
        fi
        
        if [[ -n "${{ inputs.filename_format_macos }}" ]]
        then
          echo "macos_url=https://github.com/${{ inputs.owner }}/${{ inputs.repository }}/releases/download/${{ inputs.tag_prefix }}{version}/${{ inputs.filename_format_macos }}" >> "${GITHUB_OUTPUT}"
        fi
        
        if [[ -n "${{ inputs.filename_format_windows }}" ]]
        then
          echo "windows_url=https://github.com/${{ inputs.owner }}/${{ inputs.repository }}/releases/download/${{ inputs.tag_prefix }}{version}/${{ inputs.filename_format_windows }}" >> "${GITHUB_OUTPUT}"
        fi
```

2023-11-29 14:19 UTC, quotidian-ennui commented
Ok then, I committed your suggestions, and I removed the test-install-tool yaml; I'll raise a new PR with a matrix style.

2023-12-04 18:29 UTC, stevehipwell approved these changes
Thanks @quotidian-ennui!

2023-12-04 18:33 UTC, merged